import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="bg-fixed bg-cover bg-center"
                style={{
                    backgroundImage:
                        "url(https://images.alphacoders.com/133/1339887.png)",
                }}
            >
                <AuthProvider>
                    <Navbar />
                    {/* Wrap the children in Suspense with a fallback */}
                    <AppRouterCacheProvider>
                        <Suspense fallback={<p>Loading content...</p>}>
                            {children}
                        </Suspense>
                    </AppRouterCacheProvider>
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    );
}
