# fly.toml
app = 'spaceworld'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Add these new lines below existing [http_service] keys
  [http_service.concurrency]
    soft_limit = 25
    hard_limit = 50

  [http_service.http_options]
    response = {
      "Access-Control-Allow-Origin" = "*",
      "Access-Control-Allow-Methods" = "GET,POST,PUT,DELETE,OPTIONS",
      "Access-Control-Allow-Headers" = "Content-Type,Authorization"
    }

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256