spring:
  application:
    name: games
  datasource:
    url: jdbc:sqlserver://spaceworld.database.windows.net:1433;database=postgresDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: luctra02
    password: Postgres1
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090
