spring:
  application:
    name: games
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: spring-app
  jpa:
    hibernate:
      ddl-auto: update
